__title__ = 'gearshift'
__description__ = 'Encryption at Rest tools.'
__version__ = '0.1.0'
__author__ = 'David'
__author_email__ = 'david@lenderkeycanada.com'
# __license__ = 'MIT'
__url__ = 'https://github.com/lenderkey/gearshift'
